logging:
  level:
    cn.com.partical.intelligence.education: INFO

spring:
  datasource:
    url: jdbc:mysql://DB_SRV:3306/education_v2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ieoper_v2
    password: 'ieoper_v2'

  redis:
    database: 7 # Redis服务器数据库
    host: RD_SRV  # Redis服务器地址
    password: 'ieoper'  # Redis服务器连接密码（默认为空）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

swagger:
  # 是否启用swagger，默认：true
  enabled: false

setting:
  sms:
    switch: true # 短信开关