logging:
  level:
    cn.com.partical.intelligence.education: DEBUG

spring:
  datasource:
    url: jdbc:mysql://111.229.176.19:3306/edu_v1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: '518866wsQ'

  redis:
    database: 7 # Redis服务器数据库
    host: 111.229.176.19  # Redis服务器地址
    password: '518866wsQ'  # Redis服务器连接密码（默认为空）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

swagger:
  # 是否启用swagger，默认：true
  enabled: true
